# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#
#source = $HOME/.config/hypr/gruvbox.conf

$accent = rgb(254, 128, 25)
$accentAlpha = rgb(255, 160, 102, 102)
$font = JetBrainsMono Nerd Font

# Gruvbox Dark Soft Palette
$bg = rgb(50, 48, 47)
$bg0 = rgb(60, 56, 54)
$bg1 = rgb(80, 73, 69)
$bg2 = rgb(102, 92, 84)
$bg3 = rgb(124, 111, 100)
$fg = rgb(251, 241, 199)
$text = $fg
$textAlpha = rgb(204, 251, 241, 199)

$red = rgb(251, 73, 52)
$green = rgb(184, 187, 38)
$yellow = rgb(250, 189, 47)
$blue = rgb(131, 165, 152)
$purple = rgb(211, 134, 155)
$bright_orange = rgb(254, 128, 25)
$surface0 = $bg1
$font = RobotoMono Nerd Font

general {
    hide_cursor = false
    screencopy_mode = 0
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/.config/hypr/wallpapers/arch.png
    blur_passes = 0
    color = $bg
}

#LAYOUT
label {
    monitor = 
    text = Layout: $LAYOUT
    color = $text
    font_size = 25
    font_family = $font
    position = 30, -30
    halign = left
    valign = top
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = rgb(34, 34, 35)
    font_color = $text
    fade_on_empty = false
    placeholder_text = <i>󰌾 Logged in as $USER</i>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -225
    halign = center
    valign = center
}

#FOTO
#image {
#    monitor =
#    path = $HOME/.config/hypr/lockscreen-images/teddie-p4-album.jpg
#    size = 100
#    rounding = 0
#    border_size = 1
#    border_color = $accent
#    shadow_size = 3
#    position = 0, 25
#    halign = center
#    valign = center
#}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    color = $text
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    color = $text
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

# APAGAR
label {
    monitor =
    text = ⏻
    font_size = 38
    color = $text
    onclick = systemctl poweroff

    position = 0, -305		#-80 de dist del input
    halign = center
    valign = center
}

label {
    monitor =
    text = 🗘
    font_size = 25
    color = $text
    onclick = systemctl reboot

    position = -50, -310		#-85 de dist del input
    halign = center
    valign = center
}

label {
    monitor =
    text = 
    font_size = 22
    color = $text
    onclick = systemctl suspend

    position = 50, -305		#-80 de dist del input
    halign = center
    valign = center
}

//label {
//    monitor =
//    text = $LAYOUT[en,es]
//    font_size = 24
//    onclick = hyprctl switchxkblayout all next
//
//    position = 250, -20
//    halign = center
//    valign = center
//}



