--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zraekl/.config/hypr/wallpapers/fantasy-knight-cat-armor-flowers-4k-wallpaper-uhdpaper.com-594@5@f.jpg"

-- Special
background="#0c0d0b"
foreground="#e3cfbd"
cursor="#e3cfbd"

-- Colors
color0="#0c0d0b"
color1="#965C3D"
color2="#956E52"
color3="#7F807B"
color4="#9C8973"
color5="#D7A372"
color6="#AAA090"
color7="#e3cfbd"
color8="#9e9084"
color9="#965C3D"
color10="#956E52"
color11="#7F807B"
color12="#9C8973"
color13="#D7A372"
color14="#AAA090"
color15="#e3cfbd"
